# Generated by Django 4.2.28 on 2026-08-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_fields', models.JSONField()),
                ('dose_field', models.CharField(max_length=100)),
                ('od_field', models.CharField(max_length=100)),
                ('time_field', models.CharField(max_length=100)),
                ('top_n', models.PositiveSmallIntegerField(default=2)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timepoint_runs', to='uploads.file')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timepoint_run', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timepoint_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timepoint_result', to='timepoint.run')),
            ],
        ),
    ]
