# Generated by Django 4.2.28 on 2026-06-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_seed_pipelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrun',
            name='slurm_job_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
