# Generated by Django 4.2.28 on 2026-06-04 09:35

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading/Processing'), ('UPLOADED', 'Uploaded & Verified'), ('FAILED', 'Failed')], default='UPLOADING', max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_id',
            field=models.CharField(default=uploads.models.generate_upload_id, editable=False, max_length=20, unique=True),
        ),
    ]
