# Generated by Django 4.2.30 on 2026-08-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrainQCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField(default=dict)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strainqc_result', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='StrainQCConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphism_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strainqc_config', to='projects.project')),
                ('reads_files', models.ManyToManyField(related_name='strainqc_reads', to='uploads.file')),
                ('reference_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strainqc_reference', to='uploads.file')),
            ],
        ),
    ]
